// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: healthy.proto

package cyclone_healthy

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for CycloneHealthy service

type CycloneHealthyService interface {
	Healthy(ctx context.Context, in *CycloneRequest, opts ...client.CallOption) (*CycloneResponse, error)
}

type cycloneHealthyService struct {
	c    client.Client
	name string
}

func NewCycloneHealthyService(name string, c client.Client) CycloneHealthyService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "cyclone.healthy"
	}
	return &cycloneHealthyService{
		c:    c,
		name: name,
	}
}

func (c *cycloneHealthyService) Healthy(ctx context.Context, in *CycloneRequest, opts ...client.CallOption) (*CycloneResponse, error) {
	req := c.c.NewRequest(c.name, "CycloneHealthy.Healthy", in)
	out := new(CycloneResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for CycloneHealthy service

type CycloneHealthyHandler interface {
	Healthy(context.Context, *CycloneRequest, *CycloneResponse) error
}

func RegisterCycloneHealthyHandler(s server.Server, hdlr CycloneHealthyHandler, opts ...server.HandlerOption) error {
	type cycloneHealthy interface {
		Healthy(ctx context.Context, in *CycloneRequest, out *CycloneResponse) error
	}
	type CycloneHealthy struct {
		cycloneHealthy
	}
	h := &cycloneHealthyHandler{hdlr}
	return s.Handle(s.NewHandler(&CycloneHealthy{h}, opts...))
}

type cycloneHealthyHandler struct {
	CycloneHealthyHandler
}

func (h *cycloneHealthyHandler) Healthy(ctx context.Context, in *CycloneRequest, out *CycloneResponse) error {
	return h.CycloneHealthyHandler.Healthy(ctx, in, out)
}
