// Code generated by protoc-gen-go. DO NOT EDIT.
// source: healthy.proto

package cyclone_healthy

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CycloneResponse_ResponseResult int32

const (
	CycloneResponse_Zombies CycloneResponse_ResponseResult = 0
	CycloneResponse_Sick    CycloneResponse_ResponseResult = -1
	CycloneResponse_Healthy CycloneResponse_ResponseResult = 1
)

var CycloneResponse_ResponseResult_name = map[int32]string{
	0:  "Zombies",
	-1: "Sick",
	1:  "Healthy",
}

var CycloneResponse_ResponseResult_value = map[string]int32{
	"Zombies": 0,
	"Sick":    -1,
	"Healthy": 1,
}

func (x CycloneResponse_ResponseResult) String() string {
	return proto.EnumName(CycloneResponse_ResponseResult_name, int32(x))
}

func (CycloneResponse_ResponseResult) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_741f22f95cb14d6b, []int{3, 0}
}

type CycloneRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CycloneRequest) Reset()         { *m = CycloneRequest{} }
func (m *CycloneRequest) String() string { return proto.CompactTextString(m) }
func (*CycloneRequest) ProtoMessage()    {}
func (*CycloneRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_741f22f95cb14d6b, []int{0}
}

func (m *CycloneRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CycloneRequest.Unmarshal(m, b)
}
func (m *CycloneRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CycloneRequest.Marshal(b, m, deterministic)
}
func (m *CycloneRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CycloneRequest.Merge(m, src)
}
func (m *CycloneRequest) XXX_Size() int {
	return xxx_messageInfo_CycloneRequest.Size(m)
}
func (m *CycloneRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CycloneRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CycloneRequest proto.InternalMessageInfo

type ApiInfo struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApiInfo) Reset()         { *m = ApiInfo{} }
func (m *ApiInfo) String() string { return proto.CompactTextString(m) }
func (*ApiInfo) ProtoMessage()    {}
func (*ApiInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_741f22f95cb14d6b, []int{1}
}

func (m *ApiInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApiInfo.Unmarshal(m, b)
}
func (m *ApiInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApiInfo.Marshal(b, m, deterministic)
}
func (m *ApiInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApiInfo.Merge(m, src)
}
func (m *ApiInfo) XXX_Size() int {
	return xxx_messageInfo_ApiInfo.Size(m)
}
func (m *ApiInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ApiInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ApiInfo proto.InternalMessageInfo

func (m *ApiInfo) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *ApiInfo) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type ServiceStatus struct {
	Name                 string     `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Api                  []*ApiInfo `protobuf:"bytes,2,rep,name=api,proto3" json:"api,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ServiceStatus) Reset()         { *m = ServiceStatus{} }
func (m *ServiceStatus) String() string { return proto.CompactTextString(m) }
func (*ServiceStatus) ProtoMessage()    {}
func (*ServiceStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_741f22f95cb14d6b, []int{2}
}

func (m *ServiceStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceStatus.Unmarshal(m, b)
}
func (m *ServiceStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceStatus.Marshal(b, m, deterministic)
}
func (m *ServiceStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceStatus.Merge(m, src)
}
func (m *ServiceStatus) XXX_Size() int {
	return xxx_messageInfo_ServiceStatus.Size(m)
}
func (m *ServiceStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceStatus.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceStatus proto.InternalMessageInfo

func (m *ServiceStatus) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ServiceStatus) GetApi() []*ApiInfo {
	if m != nil {
		return m.Api
	}
	return nil
}

type CycloneResponse struct {
	Code                 CycloneResponse_ResponseResult `protobuf:"varint,1,opt,name=code,proto3,enum=cyclone.healthy.CycloneResponse_ResponseResult" json:"code,omitempty"`
	Response             *ServiceStatus                 `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *CycloneResponse) Reset()         { *m = CycloneResponse{} }
func (m *CycloneResponse) String() string { return proto.CompactTextString(m) }
func (*CycloneResponse) ProtoMessage()    {}
func (*CycloneResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_741f22f95cb14d6b, []int{3}
}

func (m *CycloneResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CycloneResponse.Unmarshal(m, b)
}
func (m *CycloneResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CycloneResponse.Marshal(b, m, deterministic)
}
func (m *CycloneResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CycloneResponse.Merge(m, src)
}
func (m *CycloneResponse) XXX_Size() int {
	return xxx_messageInfo_CycloneResponse.Size(m)
}
func (m *CycloneResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CycloneResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CycloneResponse proto.InternalMessageInfo

func (m *CycloneResponse) GetCode() CycloneResponse_ResponseResult {
	if m != nil {
		return m.Code
	}
	return CycloneResponse_Zombies
}

func (m *CycloneResponse) GetResponse() *ServiceStatus {
	if m != nil {
		return m.Response
	}
	return nil
}

func init() {
	proto.RegisterEnum("cyclone.healthy.CycloneResponse_ResponseResult", CycloneResponse_ResponseResult_name, CycloneResponse_ResponseResult_value)
	proto.RegisterType((*CycloneRequest)(nil), "cyclone.healthy.CycloneRequest")
	proto.RegisterType((*ApiInfo)(nil), "cyclone.healthy.ApiInfo")
	proto.RegisterType((*ServiceStatus)(nil), "cyclone.healthy.ServiceStatus")
	proto.RegisterType((*CycloneResponse)(nil), "cyclone.healthy.CycloneResponse")
}

func init() { proto.RegisterFile("healthy.proto", fileDescriptor_741f22f95cb14d6b) }

var fileDescriptor_741f22f95cb14d6b = []byte{
	// 282 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x86, 0x9b, 0xb6, 0x50, 0xb8, 0xa8, 0x69, 0x38, 0x31, 0x44, 0x0c, 0x10, 0x79, 0xaa, 0x18,
	0x82, 0x08, 0x1b, 0x12, 0x03, 0xea, 0x02, 0x0b, 0x48, 0xc9, 0xc6, 0x44, 0x1a, 0x0e, 0xd5, 0x22,
	0x8d, 0x83, 0xed, 0x20, 0xf5, 0x31, 0x79, 0x22, 0x50, 0x6d, 0x37, 0x52, 0x5b, 0x21, 0x32, 0x5d,
	0xfe, 0xbb, 0xfb, 0xee, 0x7e, 0x1f, 0x8c, 0x17, 0x54, 0x54, 0x7a, 0xb1, 0x4a, 0x1a, 0x29, 0xb4,
	0xc0, 0x49, 0xb9, 0x2a, 0x2b, 0x51, 0x53, 0xe2, 0x64, 0x16, 0x42, 0x30, 0xb3, 0x52, 0x46, 0x9f,
	0x2d, 0x29, 0xcd, 0xae, 0x61, 0x74, 0xdf, 0xf0, 0xc7, 0xfa, 0x5d, 0x60, 0x08, 0x83, 0xa2, 0xe1,
	0x91, 0x17, 0x7b, 0xd3, 0xe3, 0x6c, 0x1d, 0xe2, 0x29, 0x1c, 0x90, 0x94, 0x42, 0x46, 0x7d, 0xa3,
	0xd9, 0x1f, 0xf6, 0x0c, 0xe3, 0x9c, 0xe4, 0x17, 0x2f, 0x29, 0xd7, 0x85, 0x6e, 0x15, 0x22, 0x0c,
	0xeb, 0x62, 0x49, 0xae, 0xd3, 0xc4, 0x78, 0x69, 0x61, 0xfd, 0x78, 0x30, 0xf5, 0xd3, 0x28, 0xd9,
	0x59, 0x24, 0x71, 0x33, 0xcd, 0x18, 0xf6, 0xed, 0xc1, 0xa4, 0x5b, 0x4b, 0x35, 0xa2, 0x56, 0x84,
	0x33, 0x18, 0x96, 0xe2, 0xcd, 0x32, 0x83, 0xf4, 0x6a, 0x0f, 0xb0, 0x53, 0x9f, 0x6c, 0x82, 0x8c,
	0x54, 0x5b, 0xe9, 0xcc, 0x34, 0xe3, 0x2d, 0x1c, 0x49, 0xa7, 0x1b, 0x0b, 0x7e, 0x7a, 0xbe, 0x07,
	0xda, 0xb2, 0x92, 0x75, 0xf5, 0xec, 0x0e, 0x82, 0x6d, 0x26, 0xfa, 0x30, 0x7a, 0x11, 0xcb, 0x39,
	0x27, 0x15, 0xf6, 0xf0, 0x04, 0x86, 0x39, 0x2f, 0x3f, 0xc2, 0x9f, 0xcd, 0xe7, 0xad, 0xf3, 0x0f,
	0x16, 0x1a, 0x7a, 0xe9, 0x6b, 0xf7, 0xd2, 0x4e, 0xc3, 0xa7, 0x2e, 0x8d, 0x17, 0x7f, 0xdb, 0x31,
	0x57, 0x39, 0x8b, 0xff, 0xf3, 0xcb, 0x7a, 0xf3, 0x43, 0x73, 0xe3, 0x9b, 0xdf, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x90, 0x81, 0x5d, 0x0d, 0xf4, 0x01, 0x00, 0x00,
}
