// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: healthy.proto

package cyclone_healthy

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Healthy service

type HealthyService interface {
	Healthy(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type healthyService struct {
	c    client.Client
	name string
}

func NewHealthyService(name string, c client.Client) HealthyService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "cyclone.healthy"
	}
	return &healthyService{
		c:    c,
		name: name,
	}
}

func (c *healthyService) Healthy(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Healthy.Healthy", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Healthy service

type HealthyHandler interface {
	Healthy(context.Context, *Request, *Response) error
}

func RegisterHealthyHandler(s server.Server, hdlr HealthyHandler, opts ...server.HandlerOption) error {
	type healthy interface {
		Healthy(ctx context.Context, in *Request, out *Response) error
	}
	type Healthy struct {
		healthy
	}
	h := &healthyHandler{hdlr}
	return s.Handle(s.NewHandler(&Healthy{h}, opts...))
}

type healthyHandler struct {
	HealthyHandler
}

func (h *healthyHandler) Healthy(ctx context.Context, in *Request, out *Response) error {
	return h.HealthyHandler.Healthy(ctx, in, out)
}
